# This file can be used to customize tox tests as well as other test frameworks like flake8 and mypy

[tox]
envlist = py39, py310, py311
isolated_build = true

[testenv]
deps =
    pytest
    black
    flake8
    pydocstyle
    mypy
    isort
    requests-mock
    types-requests
commands =
    pytest
    black --check tap_workato/
    flake8 tap_workato
    pydocstyle tap_workato
    mypy tap_workato --exclude='tap_workato/tests'

[testenv:pytest]
# Run the python tests.
# To execute, run `tox -e pytest`
deps =
    pytest
    requests-mock
commands =
    pytest

[testenv:format]
# Attempt to auto-resolve lint errors before they are raised.
# To execute, run `tox -e format`
deps =
    black
    isort
commands =
    black tap_workato/
    isort tap_workato

[testenv:lint]
# Raise an error if lint and style standards are not met.
# To execute, run `tox -e lint`
deps =
    black
    isort
    flake8
    pydocstyle
    mypy
    types-requests
commands =
    black --check --diff tap_workato/
    isort --check tap_workato
    flake8 tap_workato
    pydocstyle tap_workato
    # refer to mypy.ini for specific settings
    mypy tap_workato --exclude='tap_workato/tests'

[flake8]
ignore = W503
max-line-length = 88
max-complexity = 10

[pydocstyle]
ignore = D105,D203,D213
match = (?![(test)|(__init__)]).*\.py
